steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    [
      'functions', 'deploy', 'flask-webhook',
      '--runtime', 'python39',
      '--trigger-http',
      '--allow-unauthenticated',
      '--entry-point', 'app',
      '--region', 'europe-west1',
      '--source', '.'
    ]
